### ISSUE TITLE
Absolutely ensure that `id` is set as `pk` if no `pk` is assigned

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fastlite#48]
The spec says this happens, and tests proves that it happens. But myself and @Isaac-Flath may have seen behaviors that lead us to believe it is not working as well as it should.

Steps:

1. Confirm this is actually an issue
2. Resolve the issue

**Comment by jph00** [comment]
@pydanny can we close this now?

**Comment by pydanny** [comment]
Just tried to replicate it and I can't do it. Either APSW fixed it or it wasn't a problem.
